/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 101
#define YY_END_OF_BUFFER 102
static yyconst short int yy_accept[397] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  102,    1,  101,   39,   38,   40,   31,   39,
       29,   39,   39,   39,   38,   46,   47,   46,   46,   46,
       51,   51,   50,   49,   60,   59,   58,   55,   56,   57,
       67,   66,   65,   62,   67,   67,   63,   64,  100,   99,
       98,   97,   85,   89,   95,   70,   74,   79,   82,   70,
       84,  100,   81,   70,   72,   77,   91,   70,   94,   73,
       78,   38,    0,    0,    0,    0,   37,   30,   35,   28,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   33,   34,    0,   11,    0,    0,   38,
        0,   45,    0,    0,    0,   50,    0,    0,   48,   49,
       49,   59,   52,    0,   66,   61,   99,   96,   83,   86,
       80,   69,    0,   88,    0,    0,   71,   75,   76,   90,
       92,   93,    0,    0,    0,   10,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   38,    0,    0,
       48,   48,    0,    0,    0,    0,    8,    0,    9,   36,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   26,    0,    0,    0,    0,    0,   38,    0,

        0,    0,   87,   68,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   38,    0,    0,    0,    0,    0,    0,   15,    0,
        0,    0,   27,    0,    0,   20,    0,    0,    0,    0,
        0,    0,   38,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   32,   18,    0,   21,    0,    0,   25,
        0,    0,   38,    0,    0,    0,    0,    0,   12,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   13,    0,   17,
        0,    0,   23,   22,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   54,    0,    0,    0,    0,
        0,    0,    0,    0,    3,    0,    0,    0,    0,   44,
        0,    0,   19,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   53,   14,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    7,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       41,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   24,    0,    0,    0,    4,
        0,    0,    0,    0,    0,    0,    0,    0,    6,    2,
       42,    0,    0,    0,    5,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    2,    3,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    3,    5,    2,    2,    6,    7,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    2,    2,    2,
        2,    9,    2,   10,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       12,   13,   14,    2,   15,    2,   16,   17,   18,   19,

       20,   21,   22,   23,   24,   11,   11,   25,   26,   27,
       28,   29,   11,   30,   31,   32,   33,   34,   35,   36,
       37,   11,   38,    2,   39,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,

        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    2,    1,    1,
        2,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    1,    4
    } ;

static yyconst short int yy_base[424] =
    {   0,
      609,  608,    0,   39,  604,    4,  603,    7,   15,   18,
       78,  117,  156,  195,  234,  273,   18,   19,  308,  343,
      378,    0,  606,  611,  611,  611,    0,   33,  611,  601,
      611,  412,  600,    9,  573,  611,  611,  598,  581,  580,
      611,   31,   52,  595,  611,    0,  611,   37,  611,  611,
      611,    0,  611,  611,  594,   51,  611,  611,  611,    0,
      611,  611,  611,  611,  611,   58,  611,  611,  611,   88,
      611,  593,  611,  446,  611,  558,  611,   48,  557,  611,
      611,    0,   63,  585,  589,  588,   69,  611,  611,  611,
      558,   69,   83,   88,  570,   42,  573,  568,  559,  551,

      560,  108,   51,  611,  611,  580,  611,  116,   78,  565,
      578,  611,  554,  553,   93,  103,  110,  134,  575,  574,
      611,    0,  611,  550,    0,  611,    0,  611,  611,  611,
      611,  611,  572,  131,  533,  453,  611,  611,  611,  611,
      611,  611,  473,  477,  476,  611,  141,  470,  445,  147,
      447,  447,  441,  451,  455,  451,  449,  451,  440,  447,
      438,  426,  445,  446,  429,  438,  123,  437,  438,  436,
      450,  611,  421,  147,  439,  409,  611,  442,  611,  611,
      419,  402,  401,  412,  403,  407,  405,  398,  403,  388,
      400,  395,  611,  382,  386,  387,  387,  377,  385,  370,

      369,  382,  611,  611,  377,  380,  383,  364,  374,  376,
      363,  386,  372,  376,  357,  364,  369,  370,  367,  359,
      348,  354,  125,  360,  350,  346,  347,  344,  611,  353,
      345,  333,  611,  332,  342,  611,  330,  339,  350,  327,
      326,  325,  342,  336,  329,  339,  330,  338,  317,  327,
      327,  313,  323,  611,  611,  312,  611,  316,  317,  611,
      154,    0,  336,  307,  319,  308,  318,  316,  611,  297,
      310,  611,  295,  302,  165,  303,  302,  304,  297,  307,
      287,  310,  293,  290,  305,  300,  283,  611,  290,  611,
      279,  173,  611,  611,  283,  290,  275,  287,  276,  301,

      299,  280,  283,  285,  261,  261,  278,  259,  276,  275,
      263,  260,  275,  287,  611,    0,  256,  261,  252,  611,
      242,  238,  611,  243,  231,  246,  249,  251,  261,  245,
      246,  239,  611,  611,  232,  257,  226,  231,  226,  169,
      227,  228,  229,  227,  249,  611,  232,  233,  226,  240,
      225,  218,  193,  203,  200,  201,  202,  171,  211,  206,
      611,  193,  207,  203,  182,  182,  188,  180,  180,  201,
      195,  210,  177,  182,  611,  611,  166,  154,  187,  611,
      184,  127,  124,  116,  208,   76,   85,  105,  611,  611,
      611,   50,   72,   55,  611,  611,  485,  489,  493,  497,

      501,  505,  509,  513,   28,  517,  521,  525,  529,   23,
       14,    1,  533,  537,  541,  545,  549,  551,  555,  559,
      563,  567,  571
    } ;

static yyconst short int yy_def[424] =
    {   0,
      397,  397,  398,  398,  399,  400,  399,  400,  401,  401,
      402,  402,  403,  403,  404,  404,   16,   16,   16,   16,
       16,   21,  396,  396,  396,  396,  405,  396,  396,  406,
      396,  396,  407,   32,  405,  396,  396,  408,  396,  396,
      396,  396,  396,  409,  396,  410,  396,  396,  396,  396,
      396,  411,  396,  396,  406,  396,  396,  396,  396,  412,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  413,  396,  396,  396,  396,  396,   74,  396,  396,
      396,  405,  396,  396,  414,  406,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  407,  396,  396,  396,  405,
      408,  396,  396,  396,  396,  396,  396,  396,  415,  409,
      396,  410,  396,  396,  411,  396,  412,  396,  396,  396,
      396,  396,  413,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  416,  414,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  405,  396,  396,
      415,  396,  396,  396,  396,  396,  396,  416,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  405,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  405,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  405,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  417,  405,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      417,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  418,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  418,  396,  419,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  419,  396,
      396,  396,  396,  396,  396,  420,  396,  396,  396,  419,
      396,  396,  396,  396,  420,  396,  396,  396,  396,  419,
      396,  396,  396,  396,  396,  396,  396,  419,  396,  396,
      396,  396,  396,  396,  396,  419,  396,  396,  396,  396,
      396,  421,  419,  396,  396,  396,  396,  396,  421,  396,
      419,  396,  396,  422,  419,  396,  396,  422,  396,  396,
      396,  396,  423,  423,  396,    0,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396
    } ;

static yyconst short int yy_nxt[651] =
    {   0,
       26,   26,  127,   28,   26,   29,   30,   37,   26,   31,
       37,   26,   32,   26,   26,  125,   39,   42,   43,   40,
       42,   43,   59,   59,  122,  108,   44,   69,   69,   82,
       70,   70,  109,  115,  116,   83,   84,   26,   26,   26,
       26,   85,   28,   26,   29,   30,  123,   33,   31,  124,
       26,   34,   26,   26,  117,  118,  126,   89,  395,  140,
      119,  141,  128,  129,  130,   83,  143,  131,  156,   35,
      132,  147,  148,  157,  165,  395,   26,   26,   45,   45,
      162,   47,   45,   45,   45,   92,   45,   48,  393,   45,
       45,   45,   45,  129,  130,  115,  116,  131,  151,  150,

      132,   92,  152,  153,  167,  117,  118,  154,  389,  157,
      392,  119,  117,  118,  391,   49,   50,   45,   45,  389,
       47,   45,   45,   45,   92,   45,   48,  163,   45,   45,
       45,   45,   92,  174,  175,  166,  117,  118,  150,  164,
       92,  187,  119,  147,  148,  244,  150,  387,   92,  174,
      175,  198,  386,  245,   49,   50,   51,   51,  246,   53,
       51,   54,   55,   92,   51,   51,  163,   51,   56,   51,
       51,  277,  292,  340,  278,  340,  293,  150,  366,   92,
      292,  340,  279,  350,  293,  350,  373,  280,  385,  366,
      380,  381,  384,   57,   58,   51,   51,  383,   53,   51,

       54,   55,  294,   51,   51,  382,   51,   56,   51,   51,
      294,  390,  340,  380,  378,  366,  377,  376,  375,  374,
      372,  371,  350,  370,  369,  368,  367,  365,  364,  363,
      362,  361,   57,   58,   59,   59,  360,   61,   62,   63,
       64,  359,   59,   65,  358,   59,   66,   59,   59,  357,
      356,  355,  346,  354,  353,  352,  351,  349,  348,  347,
      346,  344,  343,  342,  341,  340,  339,  338,  337,  336,
      335,   67,   68,   59,   59,  334,   61,   62,   63,   64,
      333,   59,   65,  332,   59,   66,   59,   59,  331,  330,
      315,  328,  327,  326,  325,  324,  323,  322,  321,  320,

      319,  318,  317,  316,  315,  313,  312,  311,  310,  309,
       67,   68,   59,   71,   72,  308,  307,   73,  306,  305,
       74,  304,  303,  302,  301,  300,  299,  298,  297,  296,
      295,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  276,  275,  274,  273,   75,   76,   59,   71,   72,
      272,  271,   73,  270,  269,   74,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  253,  252,  251,  250,  249,  248,  247,  243,  242,
       75,   76,   59,   71,   72,  241,  240,   73,  239,   77,
       78,   79,  238,  237,  236,  235,  234,  233,  232,  231,

      230,  229,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  217,  216,   80,   81,   88,   89,  215,
      214,   90,  213,  212,  211,  210,  209,   91,   92,   93,
       94,  208,  207,  206,   95,   96,   97,   98,   99,  100,
      101,  205,  102,  103,   92,  179,  204,  203,  202,  104,
      105,  129,  130,  172,  201,  131,  200,  199,  132,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  135,  182,  181,  136,  180,  146,
      179,  177,  176,  137,  138,   25,   25,   25,   25,   27,
       27,   27,   27,   36,   36,   36,   36,   38,   38,   38,

       38,   41,   41,   41,   41,   46,   46,   46,   46,   52,
       52,   52,   52,   60,   60,   60,   60,   86,   86,   86,
       86,  106,  106,  106,  106,  111,  111,  111,  111,  120,
      120,  120,  120,  133,  133,  133,  133,  145,  145,  145,
      145,  171,  171,  171,  171,  178,  178,  178,  178,  281,
      281,  314,  314,  314,  314,  329,  329,  176,  329,  345,
      345,  345,  345,  379,  379,  379,  379,  388,  388,  388,
      388,  394,  394,  394,  394,  134,  173,  121,  172,  170,
      169,  112,  168,  107,  162,  161,  160,  159,  158,  155,
      149,   87,  146,  144,  142,  139,  134,   87,  121,  114,

      113,  112,  110,  107,   87,  396,   37,   37,   24,   24,
       23,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396
    } ;

static yyconst short int yy_chk[651] =
    {   0,
        3,    3,  412,    3,    3,    3,    3,    6,    3,    3,
        8,    3,    3,    3,    3,  411,    6,    9,    9,    8,
       10,   10,   17,   18,  410,   34,   10,   17,   18,  405,
       17,   18,   34,   42,   42,   28,   28,    3,    3,    4,
        4,   28,    4,    4,    4,    4,   48,    4,    4,   48,
        4,    4,    4,    4,   43,   43,   56,   56,  394,   78,
       43,   78,   66,   66,   66,   83,   83,   66,   96,    4,
       66,   87,   87,   96,  103,  393,    4,    4,   11,   11,
      103,   11,   11,   11,   11,   92,   11,   11,  392,   11,
       11,   11,   11,   70,   70,  115,  115,   70,   93,   92,

       70,   92,   93,   94,  109,  116,  116,   94,  388,  109,
      387,  116,  117,  117,  386,   11,   11,   12,   12,  384,
       12,   12,   12,   12,  102,   12,   12,  102,   12,   12,
       12,   12,  108,  134,  134,  108,  118,  118,  102,  102,
      102,  167,  118,  147,  147,  223,  108,  383,  108,  174,
      174,  167,  382,  223,   12,   12,   13,   13,  223,   13,
       13,   13,   13,  150,   13,   13,  150,   13,   13,   13,
       13,  261,  275,  340,  261,  358,  275,  150,  358,  150,
      292,  373,  261,  340,  292,  358,  366,  261,  381,  366,
      379,  373,  378,   13,   13,   14,   14,  377,   14,   14,

       14,   14,  275,   14,   14,  374,   14,   14,   14,   14,
      292,  385,  385,  372,  371,  385,  370,  369,  368,  367,
      365,  364,  385,  363,  362,  360,  359,  357,  356,  355,
      354,  353,   14,   14,   15,   15,  352,   15,   15,   15,
       15,  351,   15,   15,  350,   15,   15,   15,   15,  349,
      348,  347,  345,  344,  343,  342,  341,  339,  338,  337,
      336,  335,  332,  331,  330,  329,  328,  327,  326,  325,
      324,   15,   15,   16,   16,  322,   16,   16,   16,   16,
      321,   16,   16,  319,   16,   16,   16,   16,  318,  317,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,

      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
       16,   16,   19,   19,   19,  291,  289,   19,  287,  286,
       19,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  274,  273,  271,  270,  268,  267,  266,  265,  264,
      263,  259,  258,  256,  253,   19,   19,   20,   20,   20,
      252,  251,   20,  250,  249,   20,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  235,  234,
      232,  231,  230,  228,  227,  226,  225,  224,  222,  221,
       20,   20,   21,   21,   21,  220,  219,   21,  218,   21,
       21,   21,  217,  216,  215,  214,  213,  212,  211,  210,

      209,  208,  207,  206,  205,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  192,   21,   21,   32,   32,  191,
      190,   32,  189,  188,  187,  186,  185,   32,   32,   32,
       32,  184,  183,  182,   32,   32,   32,   32,   32,   32,
       32,  181,   32,   32,   32,  178,  176,  175,  173,   32,
       32,   74,   74,  171,  170,   74,  169,  168,   74,  166,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  153,  152,   74,  151,  149,   74,  148,  145,
      144,  143,  136,   74,   74,  397,  397,  397,  397,  398,
      398,  398,  398,  399,  399,  399,  399,  400,  400,  400,

      400,  401,  401,  401,  401,  402,  402,  402,  402,  403,
      403,  403,  403,  404,  404,  404,  404,  406,  406,  406,
      406,  407,  407,  407,  407,  408,  408,  408,  408,  409,
      409,  409,  409,  413,  413,  413,  413,  414,  414,  414,
      414,  415,  415,  415,  415,  416,  416,  416,  416,  417,
      417,  418,  418,  418,  418,  419,  419,  135,  419,  420,
      420,  420,  420,  421,  421,  421,  421,  422,  422,  422,
      422,  423,  423,  423,  423,  133,  124,  120,  119,  114,
      113,  111,  110,  106,  101,  100,   99,   98,   97,   95,
       91,   86,   85,   84,   79,   76,   72,   55,   44,   40,

       39,   38,   35,   33,   30,   23,    7,    5,    2,    1,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lit-deatify.lex"
#define INITIAL 0
#line 2 "lit-deatify.lex"
#if 0
\section[De-at-ifier]{Handles `at' and `tr' shorthands}

[Taking over from lit-inputter, minus the LITINPUTS stuff]

Has to know whether \tr{lit2pgm}, \tr{lit2latex} or \tr{lit2texi}
(grabbed from deviously-passed command-line argument).

And makes index entries appear well-behaved (same as \tr{\tr}, really).

And nukes [most] comments (sigh).

\subsection[deatify_Definitions]{Lex definitions}

Here, we use \tr{lex} ``start conditions'' a lot; we keep a stack of
them and manipulate them in a fairly obvious way.  Using start
conditions like this gives you ``mini-lexers'' within the overall
lexer.
\begin{code}
#endif
#line 24 "lit-deatify.lex"
/* Hacky definition of yywrap: see flex doc.

   If we don't do this, then we'll have to get the default
   yywrap from the flex library, which is often something
   we are not good at locating.  This avoids that difficulty.
   (Besides which, this is the way old flexes (pre 2.4.x) did it.)
   WDP 96/01/15
*/
#define yywrap() 1

#define LEX_STK_SIZE 256

int lex_stk[LEX_STK_SIZE];
int lex_stk_top = 0;

#define PUSH(x)    	   lex_stk[++lex_stk_top] = (x); BEGIN(x)
#define POP        	   BEGIN(lex_stk[--lex_stk_top])
#define LEX_STK_TOP	   lex_stk[lex_stk_top]
#define LEX_NEXT_TO_STK_TOP lex_stk[lex_stk_top - 1]
#define CHG_TOP(x)	   lex_stk[lex_stk_top] = (x); BEGIN(x)
#define CHG_NEXT_TO_TOP(x) lex_stk[lex_stk_top - 1] = (x)
/* not a lot in the old stack {over,under}flow dept, what? */

void print_leading_whitespace(void);

void
print_lex_stk () /* just for debugging */
{
    int i;
    fprintf(stderr,"lex_stk:");
    for (i = lex_stk_top; i >= 0; i--) {
        fprintf(stderr," %d",lex_stk[i]);
    }
    fprintf(stderr,"::%s\n",yytext);
}
#if 0
\end{code}

Things related to handling \tr{\input} commands (not doing this at the
moment):
\begin{code}
#endif
int verbose;	   /* set from first argv */
int follow_inputs; /* set from second argv */

#include "config.h"

#if defined(STDC_HEADERS) || defined(HAVE_STRING_H)
#include <string.h>
/* An ANSI string.h and pre-ANSI memory.h might conflict.  */
#if !defined(STDC_HEADERS) && defined(HAVE_MEMORY_H)
#include <memory.h>
#endif /* not STDC_HEADERS and HAVE_MEMORY_H */
#define index strchr
#define rindex strrchr
#define bcopy(s, d, n) memcpy ((d), (s), (n))
#define bcmp(s1, s2, n) memcmp ((s1), (s2), (n))
#define bzero(s, n) memset ((s), 0, (n))
#else /* not STDC_HEADERS and not HAVE_STRING_H */
#include <strings.h>
/* memory.h and strings.h conflict on some systems.  */
#endif /* not STDC_HEADERS and not HAVE_STRING_H */

#define INPUTFILE_STK_SIZE 20
struct {
    YY_BUFFER_STATE handle; /* flex-supplied magic */
    char* 	    name;
    int   	    lineno;
} inputfile_stk[INPUTFILE_STK_SIZE];
int   inputfile_stk_top = 0;
void  push_inputfile();
void  pop_inputfile();
int   i; /* temporary */
char* rbrace;

/* ----------------- */

int deatify_debug       = 0;
int unmatched_lbraces   = 0;
int unmatched_lbrackets = 0;

/* like everything, must track srcfile name and lineno */
char srcfile_name[1024]; /* too lazy to do this right */
int  lineno = 1; /* count \n's as they go by */
int  lineno_fiddled = 0; /* boolean: incr if newlines get trashed */

int  exit_status = 0;
void not_OK ();  /* prints an error msg and bumps exit_status */
void warning (); /* same, but no exit-status fiddling */

int lit2what; /* set from ARGV */

#define IS_LIT2PGM_Q	(lit2what == 1)
#define IS_LIT2PGM	(lit2what == 2)
#define IS_LIT2TEXI	(lit2what == 3)
#define IS_LIT2LATEX	(lit2what == 4)
#define IS_LIT2DEPEND	(lit2what == 5)
#define IS_LIT2CHANGELOG (lit2what== 6)

/* the condition for printing to stdout */
#define SHLD_PRINT	(! IS_LIT2PGM_Q || (LEX_STK_TOP == Code || LEX_STK_TOP == Bird))

void myecho();
#define MYECHO myecho()
void myprintstr();

#define YY_USER_ACTION if (deatify_debug) print_lex_stk(); /* debugging */
#define Norm 1
#define Verb 2
#define Code 3
#define Bird 4
#define Atting 5
#define Math 6
#define Index 7
#define Typing 8
#define Linify_braces 9
#define Linify_brackets 10


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 136 "lit-deatify.lex"

	CHG_TOP(Norm); /* that's where we start */

#if 0
\end{code}

\subsection[deatify_Rules]{Lex rules}

We start as @<Norm>@ and branch off to one of the other
``mini-scanners'' when we see certain things.

First: some magic characters absolutely verboten in the input:
\begin{code}
#endif


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 397 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 611 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 151 "lit-deatify.lex"
{ not_OK("ASCII chars \001, \002, \003 may not appear in literate files\n");
			  exit(1);
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 155 "lit-deatify.lex"
{
		  sscanf(yytext+10,"%[^!]!_!%d", srcfile_name, &lineno);
		  if (lineno > 0) {
		     ECHO;
		  }
		}
	YY_BREAK

#if 0
\end{code}

Now a bit of stuff to handle \tr{\input} lines:
\begin{code}
#endif

case 3:
YY_RULE_SETUP
#line 169 "lit-deatify.lex"
{ lineno++;
					  if (follow_inputs) {
					      /* nullify first right brace */
					      rbrace = index(yytext+7,'}');
					      *rbrace = '\0';
					      push_inputfile(yytext+7);
					  } else {
					      MYECHO;
					  }
					}
	YY_BREAK
case YY_STATE_EOF(Norm):
case YY_STATE_EOF(Bird):
#line 179 "lit-deatify.lex"
{ if ( inputfile_stk_top <= 0 ) {
			     yyterminate();
			  } else {
			     pop_inputfile();
			  }
			  CHG_TOP(Norm); /* revert */
			}
	YY_BREAK

#if 0
\end{code}


Code and verbatim stuff gets copied through absolutely unmangled,
using the @<Verb>@ (or almost equivalently @<Code>@) mini-scanner.
\begin{code}
#endif

case 4:
#line 197 "lit-deatify.lex"
case 5:
#line 198 "lit-deatify.lex"
case 6:
YY_RULE_SETUP
#line 198 "lit-deatify.lex"
{ lineno++; MYECHO; PUSH(Verb); /* some may have opt arg */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 199 "lit-deatify.lex"
{ lineno++;
				  if (IS_LIT2PGM_Q) {
				      printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,lineno);
				  }
				  MYECHO;
				  PUSH(Code);
				}
	YY_BREAK

#if 0
\end{code}

Then there is the \tr{>} business; the ugliest way ever invented for
writing programs.  You can only get there from \tr{<Norm>}, because I
said so.

\begin{code}
#endif

case 8:
YY_RULE_SETUP
#line 217 "lit-deatify.lex"
{ /* convert to something less weird & try again */
			  unput('>'); unput('\n'); unput('\n');
			}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 220 "lit-deatify.lex"
{ lineno += 3;
			  /* NB: init > converted to space */
			  if (IS_LIT2PGM_Q) {
			      printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,(lineno-1));
			      printf("%s",yytext+3);
			  } else {
			      ECHO;
			  }
			  PUSH(Bird);
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 230 "lit-deatify.lex"
{ lineno++; /* so msg will have right line # */
			  if (lineno > 2) /* I feel guilty about this hack */
			      /* to avoid: file is: blank lines, then code */
			      not_OK("Bird-style code not preceded by a blank line\n");
			  lineno++; /* account for other \n */
			  if (IS_LIT2PGM_Q) {
			      printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,(lineno-1));
			      printf("%s",yytext+2);
			  } else {
			      ECHO;
			  }
			  PUSH(Bird);
			}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 243 "lit-deatify.lex"
{ lineno++; /* first line of file */
			  if (IS_LIT2PGM_Q) {
			      printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,(lineno-1));
			      printf("%s",yytext+1);
			  } else {
			      ECHO;
			  }
			  PUSH(Bird);
			}
	YY_BREAK

#if 0
\end{code}

There are a few macros (\tr{\section}, \tr{\author}, and the others
below) that may have funny \tr{@...@}s, etc., in them (meaning
newlines would be inserted normally); these newlines must be
suppressed!  These macros send us off to \tr{<Linify_braces>} or
\tr{<Linify_brackets>}, which are like \tr{<Norm>} except that the
\tr{unput} newlines (below) get munched.  (This is getting really
horrible...)

\begin{code}
#endif

case 12:
YY_RULE_SETUP
#line 267 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 268 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 269 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 270 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 271 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 272 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 273 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 274 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 275 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 276 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 277 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 278 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_brackets); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 279 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 280 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 281 "lit-deatify.lex"
{ MYECHO; unmatched_lbraces = 1; PUSH(Typing);
				  /* \tr has braces as literals */
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 284 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_brackets); }
	YY_BREAK

#if 0
\end{code}

Similarly, an \tr{@} sends us off to @<Atting>@.  Of course, a \tr{\@} does not.
\begin{code}
#endif

case 28:
YY_RULE_SETUP
#line 293 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 294 "lit-deatify.lex"
{ myprintstr("\\codeInText{"); PUSH(Atting); }
	YY_BREAK

#if 0
\end{code}

Simple math mode stuff.

\begin{code}
#endif

case 30:
YY_RULE_SETUP
#line 304 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 305 "lit-deatify.lex"
{ myprintstr("\\MathMode{"); PUSH(Math); }
	YY_BREAK

#if 0
\end{code}

For index commands, we want them to be at the beginning of a line (we do?);
hence the @printf@s here.  The internal magic is done by
@<Index>@.
\begin{code}
#endif

case 32:
YY_RULE_SETUP
#line 316 "lit-deatify.lex"
{ MYECHO;
			  unmatched_lbraces = 1;
                          PUSH(Index);
                        }
	YY_BREAK

#if 0
\end{code}

The rest of the @<Norm>@ mini-scanner handles comments and echoes
everything else.
\begin{code}
#endif

case 33:
YY_RULE_SETUP
#line 329 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 330 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 331 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 332 "lit-deatify.lex"
{ /* technically this Bird-style code is wrong
				     (no blank line in front of it, but that's
				     not intuitively obvious to the casual observer).
				     Solution? A hack!
				  */
				  unput('>'); unput('\n'); unput('\n');
				}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 339 "lit-deatify.lex"
{ /* throw away */ lineno++;
				  if (! IS_LIT2PGM_Q)
				     printf("\nsrcfile!_!%s!_!%d!_!\n",srcfile_name,lineno);
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 343 "lit-deatify.lex"
{ MYECHO; /* slight efficiency */ }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 344 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 345 "lit-deatify.lex"
{ /* handle line-number fiddling */
				  MYECHO;
				  lineno++;
				  if (lineno_fiddled) {
				      if (! IS_LIT2PGM_Q)
				         printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,lineno);
				      lineno_fiddled = 0;
				  }
				}
	YY_BREAK

#if 0
\end{code}

The \tr{<Verb>} and \tr{<Code>} mini-scanners pass everything through until it sees an
\tr{\end <something>}.  As it stands, the \tr{<something>} does not
have to be what was \tr{\begun} (bug).
\begin{code}
#endif

case 41:
#line 365 "lit-deatify.lex"
case 42:
#line 366 "lit-deatify.lex"
case 43:
YY_RULE_SETUP
#line 366 "lit-deatify.lex"
{ MYECHO; POP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 367 "lit-deatify.lex"
{ if (! IS_LIT2PGM_Q) ECHO; POP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 368 "lit-deatify.lex"
{ lineno++; MYECHO; /* a line not started by \ */}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 369 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 370 "lit-deatify.lex"
{ lineno++; MYECHO; }
	YY_BREAK
case YY_STATE_EOF(Verb):
case YY_STATE_EOF(Code):
#line 371 "lit-deatify.lex"
{ not_OK("unexpected end-of-file in verbatim text or (pseudo)code\n");
				  exit(1);
				}
	YY_BREAK

#if 0
\end{code}

The \tr{<Bird>} mini-scanner is here only to check for
no-blank-line-after errors in uglyly-written code.
\begin{code}
#endif

case 48:
YY_RULE_SETUP
#line 383 "lit-deatify.lex"
{ /* whitespace/blank-lines do not matter */
			  /* count lines... */
			  for (i = 0; i < strlen(yytext); i++) {
			      if (yytext[i] == '\n')
			      	  lineno++;
			  }
			  if (! IS_LIT2PGM_Q) {
			    ECHO;
			  } else { /* don't print leading whitestuff */
			      for (i = 0; i < strlen(yytext) && yytext[i] != '>'; i++)
				  ; /* no-op */
			      /* report where this got us...*/
			      printf("srcfile!_!%s!_!%d!_!\n",srcfile_name,
				((yytext[yyleng-1] == '\n') ? (lineno-1) : lineno));
			      /* putchar(' '); convert leading > to space */
			      for ( i++ ; i < strlen(yytext); i++)
				  putchar(yytext[i]);
			  }
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 402 "lit-deatify.lex"
{ if (yytext[yyleng-1] == '\n') { lineno++; }
			  if (IS_LIT2PGM_Q) printf("%s",yytext+1); else ECHO;
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 405 "lit-deatify.lex"
{ lineno++;
			  if ( ! IS_LIT2PGM_Q) ECHO;
			  POP;
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 409 "lit-deatify.lex"
{ lineno--; /* to get right # on msg */
			  not_OK("Bird-style code not followed by a blank line\n");
			  lineno++; /* put it back */
			  unput(yytext[0]);
			  POP;
			}
	YY_BREAK

#if 0
\end{code}

\tr{<Typing>} and \tr{<Index>} deal with braces the same way: these
rules must come before the default rules for \tr{<Typing>.} and
\tr{<Index>.}.

The rule of the @<Atting>@ game is to send everything through except
right braces and newlines (which break the use of @/[^\}]+/@ regexps).
No longer worry about one per line.

\begin{code}
#endif

case 52:
YY_RULE_SETUP
#line 430 "lit-deatify.lex"
{ myprintstr("@"); }
	YY_BREAK
case 53:
#line 432 "lit-deatify.lex"
case 54:
YY_RULE_SETUP
#line 432 "lit-deatify.lex"
{ myprintstr("\001noindex\003}");
			  POP;
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 435 "lit-deatify.lex"
{ myprintstr("}");
			  POP;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 438 "lit-deatify.lex"
{ myprintstr("\001lbrace\003"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 439 "lit-deatify.lex"
{ myprintstr("\001rbrace\003"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 440 "lit-deatify.lex"
{ warning("I'm turning a newline inside a @...@ into a space\n");
			  myprintstr(" ");
			  lineno++;
			}
	YY_BREAK
case YY_STATE_EOF(Atting):
#line 445 "lit-deatify.lex"
{ not_OK("unexpected end-of-file inside an @ ... @\n");
			  exit(1);
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 448 "lit-deatify.lex"
{ MYECHO; /* tiny efficiency */ }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 449 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK

#if 0
\end{code}

Math mode stuff.  At present, only extra work is to replace some
control sequences with plain text---for \tr{lit2texi} only.

\begin{code}
#endif

case 61:
YY_RULE_SETUP
#line 460 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 461 "lit-deatify.lex"
{ myprintstr("}");
			  POP;
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 464 "lit-deatify.lex"
{ myprintstr("\001lbrace\003"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 465 "lit-deatify.lex"
{ myprintstr("\001rbrace\003"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 466 "lit-deatify.lex"
{ myprintstr("\001newline\003");
			  lineno++;
			}
	YY_BREAK
case YY_STATE_EOF(Math):
#line 470 "lit-deatify.lex"
{ not_OK("unexpected end-of-file inside $ ... $ (math mode)\n");
			  exit(1);
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 473 "lit-deatify.lex"
{ MYECHO; /* tiny efficiency */ }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 474 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK

#if 0
\end{code}

The braces/brackets stuff isn't too bad.  Well, there's the stuff for
\tr{\tr} and \tr{@..@}'s (no \tr{\index}'s now...) ...
\begin{code}
#endif

case 68:
YY_RULE_SETUP
#line 484 "lit-deatify.lex"
{
			  MYECHO;
			  unmatched_lbraces = 1;
			  PUSH(Typing);
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 490 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 493 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 496 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 500 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_braces); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 501 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 503 "lit-deatify.lex"
{ unmatched_lbraces++; myprintstr("\001lbrace\003"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 505 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 508 "lit-deatify.lex"
{ /* next arg */ MYECHO; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 510 "lit-deatify.lex"
{ MYECHO; POP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 511 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 513 "lit-deatify.lex"
{ if (--unmatched_lbraces == 0) {
			      MYECHO;
                              POP;
                          } else {
			      myprintstr("\001rbrace\003");
                          }
                        }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 521 "lit-deatify.lex"
{
			  MYECHO;
			  /* Note: our pseudo-makeindex has two magic chars */
			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 525 "lit-deatify.lex"
{
			  myprintstr("\\codeInText{"); /* no newline */
			  PUSH(Atting); 
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 529 "lit-deatify.lex"
{ MYECHO; /* NB: magic <Index> chars below */ }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 531 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 534 "lit-deatify.lex"
{
			  myprintstr("\\MathMode{"); /* no newline */
			  PUSH(Math);
			}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 538 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 540 "lit-deatify.lex"
{
			  MYECHO;
			}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 543 "lit-deatify.lex"
{
			  /* see earlier comments about crimes against humanity */
			  unput('>'); unput('\n'); unput('\n');
			}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 547 "lit-deatify.lex"
{ /* throw away */
			  lineno++;
			  lineno_fiddled++;
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 551 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 553 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 554 "lit-deatify.lex"
{ MYECHO; PUSH(Linify_brackets); }	
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 556 "lit-deatify.lex"
{ myprintstr("\\\001rbracket\003"); /* cannot have these in the way */ }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 557 "lit-deatify.lex"
{ if (LEX_NEXT_TO_STK_TOP == Norm) {
			      MYECHO;
			  } else {
			      myprintstr("\001rbracket\003\{");
			      not_OK("WHAT'S GOING ON? ]{\n");
			      print_lex_stk();
			  }
			  CHG_TOP(Linify_braces);
                        }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 566 "lit-deatify.lex"
{ if (LEX_NEXT_TO_STK_TOP == Norm) {
			      MYECHO;
			  } else {
			      myprintstr("\001rbracket\003");
			  }
			  POP;
                        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 574 "lit-deatify.lex"
{ myprintstr("\001idxsort\003"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 575 "lit-deatify.lex"
{ MYECHO; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 576 "lit-deatify.lex"
{ myprintstr("\001idxsubitem\003"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 578 "lit-deatify.lex"
{
			  lineno++;
			  lineno_fiddled++;
			  if (LEX_STK_TOP == Index) {
			     warning("I'm turning a newline inside an \\index{...} into a space\n");
			     myprintstr(" ");
			  } else if (LEX_STK_TOP == Typing) {
			     warning("I'm turning a newline inside a \\tr{...} or \\pl{...} into a space\n");
			     myprintstr(" ");
			  } else {
			     myprintstr("\001newline\003");
			  }
			}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 592 "lit-deatify.lex"
{
			  MYECHO; /* tiny efficiency */
			}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 596 "lit-deatify.lex"
{ MYECHO; /* catch all */ }
	YY_BREAK
case YY_STATE_EOF(Index):
#line 598 "lit-deatify.lex"
{ not_OK("unexpected end-of-file inside an \\index{...}\n");
			  exit(1);
			}
	YY_BREAK
case YY_STATE_EOF(Linify_braces):
#line 601 "lit-deatify.lex"
{ not_OK("unexpected end-of-file inside a macro argument\n");
			  exit(1);
			}
	YY_BREAK
case YY_STATE_EOF(Linify_brackets):
#line 604 "lit-deatify.lex"
{not_OK("unexpected end-of-file inside a macro optional argument\n");
			  exit(1);
			}
	YY_BREAK
case YY_STATE_EOF(Typing):
#line 607 "lit-deatify.lex"
{ not_OK("unexpected end-of-file inside a \\tr{...}\n");
			  exit(1);
			}
	YY_BREAK

#if 0
\end{code}

Finally, we have a non-default @main@ routine because we need to pick
up the (mandatory) argument that says if we are doing pre-processing
for \tr{lit2pgm}, \tr{lit2latex}, or \tr{lit2texi}.
\begin{code}
#endif

case 101:
YY_RULE_SETUP
#line 620 "lit-deatify.lex"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 2);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 397 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 2;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 397 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 396);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 620 "lit-deatify.lex"


main(argc, argv)
int  argc;
char **argv;
{
    if (argc != 5) {
	fprintf(stderr,"Sorry, %s must have exactly 4 arguments\n", argv[0]);
	exit(1);
    }
    verbose	  = argv[1][0] - '0'; /* hacks */
    follow_inputs = argv[2][0] - '0';
    lit2what      = argv[3][0] - '0'; /* used in IS_LIT2xxx tests */
    if (strcmp(argv[4], "-") == 0) {
	yyin = stdin;
    } else if ((yyin = fopen(argv[4], "r")) == NULL) {
	fprintf(stderr,"%s: can't open file %s\n", argv[0], argv[4]);
	exit(1);
    }
    strcpy(srcfile_name, argv[4]);
    inputfile_stk[ inputfile_stk_top /* 0 */ ].name = argv[4];
    if ( ! IS_LIT2PGM_Q ) printf("srcfile!_!%s!_!1!_!\n",argv[4]);
    yylex();
    exit(exit_status);
}

void
push_inputfile (fname)
char* fname;
{
    if ( inputfile_stk_top >= INPUTFILE_STK_SIZE ) {
	fprintf(stderr,"\\input's too deeply nested\n");
	exit(1);
    }

    /* record where we are in current file */
    inputfile_stk[ inputfile_stk_top ].lineno   = lineno;
    inputfile_stk[ inputfile_stk_top ].handle = YY_CURRENT_BUFFER;
    /* actual push */
    inputfile_stk_top++;

    /* open new file fname */
    if ((yyin = fopen(fname, "r")) == NULL) {
	fprintf(stderr,"%s:%d: can't open \\input file %s\n", srcfile_name, lineno, fname);
	exit(1);
    }
    yy_switch_to_buffer( yy_create_buffer( yyin, YY_BUF_SIZE ) );

    /* report that's where we are */
    if (! IS_LIT2PGM_Q) printf("srcfile!_!%s!_!1!_!\n",fname);
    /* set srcfile_name and lineno for new file */

    strcpy(srcfile_name, fname); /* for my own tracking */
    lineno = 1;

    /* push/record everything for new file */
    inputfile_stk[ inputfile_stk_top ].name     = srcfile_name;
    inputfile_stk[ inputfile_stk_top ].lineno   = lineno;
}

void
pop_inputfile ()
{
    inputfile_stk_top--; /* actual pop */

    /* remind where we were */
    strcpy(srcfile_name, inputfile_stk[inputfile_stk_top].name);
    lineno       = inputfile_stk[inputfile_stk_top].lineno;
    /* put in an extra newline or two before the next file;
       otherwise, the cat'ting of files gives things like:

       > last line of code
       \section{Next section}

       which happens to be very bad for lit2stuff.
    */
    if (! IS_LIT2PGM_Q) printf("\n\nsrcfile!_!%s!_!%d!_!\n",srcfile_name,lineno);

    /* return to prev inputfile */
    yy_switch_to_buffer( inputfile_stk[inputfile_stk_top].handle );
}

void
myecho ()
{
    myprintstr(yytext);
}

void
myprintstr (str)
char *str;
{
    if (SHLD_PRINT) {
	printf("%s",str);
    }
}

void
print_leading_whitespace (void)
{
    int i;
    
    for (i = 0; yytext[i] == ' ' || yytext[i] == '\t'; i++) {
    	putchar(yytext[i]);
    }
}

void
not_OK(msg)
char *msg;
{
    /* a good old emacsable error msg */
    fprintf(stderr,"%s:%d: %s", srcfile_name, lineno, msg);
    exit_status++;
}

void
warning(msg) /* exit_status not fiddled */
char *msg;
{
    /* a good old emacsable warning msg */
    fprintf(stderr,"%s:%d: [warning] %s", srcfile_name, lineno, msg);
}
#if 0
\end{code}
#endif
